### ISSUE TITLE
Options Menu Icon Support

### ISSUE THREAD

**Issue by suleymanccelik** [MajeurAndroid/Android-Cling#1]
I am trying to add cling to my options menu on the toolbar, but gives me " java.lang.IllegalArgumentException: width and height must be > 0 " error.

ClingManager mClingManager = new ClingManager(MainActivity.this);
mClingManager.addCling(new Cling.Builder(this)
                .setTitle(R.string.popup_title)
                .setContent(R.string.logout_content)
                .setMessageBackground(getResources().getColor(R.color.primary_dark))
                .setTarget(new ViewTarget(this, R.id.action_search))
                .build());
mClingManager.start();

OS Version : Android 6.0.1

**Comment by MajeurAndroid** [comment]
Use ActionItemTarget
see: dbc95b043bd7cfe08db93b6c444100005ec02191
Thanks

**Comment by maxkeppeler** [comment]
This doesn't seem to work anymore.

**Comment by MajeurAndroid** [comment]
Could you describe more precisely what doesn't work anymore.

**Comment by maxkeppeler** [comment]
No matter where, as soon as an menu action is is the target, it will result in a NullPointer. :/

**Comment by MajeurAndroid** [comment]
If you use the ActionItemTarget, a NPE is thrown only if the MenuItem has no View attached to itself; eg is not shown in ActionBar. This is why it is recomended to set the attribute showAsAction to "always".
Also can you post the message of the NPE.

**Comment by maxkeppeler** [comment]
All MenuItems have the attribute showAsAction set to "always" already. I will be able to work on it ad add Cling again and will send you then the NPE. Thanks for the reply.
