### ISSUE TITLE
How to include this library into project via gradle dependency?

### ISSUE THREAD

**Issue by eternalBlast** [MajeurAndroid/Android-Cling#2]
Hello, MajeurAndroid. this is awesome library for tutoring the user to apps. But, How to include this library into project via gradle dependency? Thanks

**Comment by MajeurAndroid** [comment]
I'm working on this ! 
For now just go to project release tab and download the aar.
Then simply put aar in yourModule/libs/
Finally add in your dependencies scope:
compile ':downloadedfilename@aar'

**Comment by MajeurAndroid** [comment]
Done !
jcenter support is planned but it does not work for now ...
see ab03d5501fe4578dd98a49a090fad24962fa4097
