### ISSUE TITLE
Decrease size of cling circle?

### ISSUE THREAD

**Issue by F-Tahir** [MajeurAndroid/Android-Cling#5]
Hi, I'm trying to do just as the title says. I have small icons in my UI (it's a camera app of sorts), and so one cling often covers one and a half icons. Is there any way to decrease the size of the cling circle?

**Comment by MajeurAndroid** [comment]
The circle size is calculated with your icon's view dimensions. There is now way of decrease as of today. But the circle should mainly point to the icon you want.
